Added logic to handle Failed and Cancelled builds.

diff --git a/deploy/sre-build-test/50-build-test.CronJob.yaml b/deploy/sre-build-test/50-build-test.CronJob.yaml
--- a/deploy/sre-build-test/50-build-test.CronJob.yaml
+++ b/deploy/sre-build-test/50-build-test.CronJob.yaml
@@ -42,8 +42,19 @@ spec:
               oc -n $NS new-build nodejs~https://github.com/openshift/nodejs-ex --name=sre-build-test; 
               echo $(date): Waiting for build to complete.; 
               while :; 
-              do 
-                oc -n $NS get build -o custom-columns=STATUS:.status.phase --no-headers | grep Complete && break; 
+              do  
+                export ST=$(oc -n $NS get build -o custom-columns=STATUS:.status.phase --no-headers);
+                echo Checking the state of the build: $ST;
+                if [[ $ST = "Failed" ]]
+                then 
+                echo "Build Failed" && exit 1
+                elif [[ $ST = "Cancelled" ]]
+                then
+                echo "Build was Cancelled" && exit 1
+                elif [[ $ST = "Complete" ]]
+                then
+                echo "Build Complete" && break
+                fi 
                 echo $(date): Checking build again in 15 seconds, NS=$NS; 
                 sleep 15; 
               done; 
