Needed extra logic for when no installplans found

diff --git a/deploy/osd-route-monitor-operator-reinstall/04-openshift-route-monitor-operator.CronJob.yaml b/deploy/osd-route-monitor-operator-reinstall/04-openshift-route-monitor-operator.CronJob.yaml
--- a/deploy/osd-route-monitor-operator-reinstall/04-openshift-route-monitor-operator.CronJob.yaml
+++ b/deploy/osd-route-monitor-operator-reinstall/04-openshift-route-monitor-operator.CronJob.yaml
@@ -33,8 +33,11 @@ spec:
               CSV_FOUND=$(oc -n "$NAMESPACE" get clusterserviceversions.operators.coreos.com -o name | grep "$OPERATOR")
               if [[ ! -z "$CSV_FOUND" ]]; then
                 # The OLM dance
-                # delete all installplans
-                oc get installplans.operators.coreos.com -n $NAMESPACE | grep $OPERATOR | awk '{print $1}' | xargs oc delete installplan.operators.coreos.com -n $NAMESPACE
+                # delete all installplans (if found) (the true is so we don't fail set -e)
+                installplans=$(oc get installplans.operators.coreos.com -n "$NAMESPACE" | grep "$OPERATOR" || true | awk '{print $1}')
+                if [[ -n "$installplans" ]]; then
+                  echo "$installplans" | xargs oc delete installplan.operators.coreos.com -n "$NAMESPACE"
+                fi
                 # get subscription
                 oc get subscription.operators.coreos.com -n $NAMESPACE $OPERATOR -o json | jq 'del(.status) | del(.metadata.creationTimestamp) | del(.metadata.generation) | del(.metadata.resourceVersion) | del(.metadata.uid)' > /tmp/sub.json
                 # delete subscription
